language: go
cache:
  directories:
    - ${GOPATH}/src/github.com/axw/gocov/gocov
    - ${GOPATH}/src/github.com/golang/lint
    - ${GOPATH}/src/github.com/mattn/goveralls
    - ${GOPATH}/src/github.com/stretchr
    - ${GOPATH}/src/golang.org/x/crypto
    - ${GOPATH}/src/golang.org/x/tools
go: 1.4
sudo: false

install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify
  - go get golang.org/x/crypto/bcrypt
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -cover ./...
  - golint ./...

after_success:
  - go test -v -covermount=count -coverprofile=coverage.out ${HOME}/gopath/bin/goveralls -service=travis-ci -repotoken ${COVERALLS_TOKEN}
